import { main } from "./main.mjs"

const data = `...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`

let res = main(data)
console.assert(res == 374)
console.log("Got:", res)